settings-en:
  path: src/content/en/settings
  glob:
    - '**/*.{json,yml,yaml}'
  name: Settings (English)
  icon: settings
  disable_url: false
  preview:
    text:
      - key: company.name
  _enabled_editors:
    - data
  disable_add: false
  disable_add_folder: false
  disable_file_actions: false
