// Astro 5 content collections — locale_routed branch (per Phase 1 handoff §5).
// Each locale gets parallel collections; routes read `pages-{locale}` etc.
// All-auto translation per Phase 5 Turn 1: EN is source of truth, es/en-ca/fr-ca
// are generated by translate-loader at build (Phase 5 §lib/translate-loader.ts).

import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const pageSchema = z.object({
  title: z.string(),
  description: z.string().nullish(),
  ogImage: z.string().nullish(),
  publishedAt: z.coerce.date().nullish(),
  updatedAt: z.coerce.date().nullish(),
  draft: z.boolean().default(false),
  structuredData: z.any().nullish(),
  content_blocks: z.array(z.object({ _type: z.string() }).passthrough()).default([]),
});

const blogSchema = pageSchema.extend({
  excerpt: z.string().nullish(),
  author: z.string().nullish(),
  category: z.string().nullish(),
  tags: z.array(z.string()).default([]),
  hero: z.string().nullish(),
});

const serviceSchema = z.object({
  title: z.string(),
  summary: z.string().nullish(),
  href: z.string(),
});

const faqSchema = z.object({
  question: z.string(),
  answer: z.string(),
  order: z.number().default(0),
});

const settingsSchema = z.object({
  company: z.object({
    name: z.string().nullish(),
    parent: z.string().nullish(),
    phone: z.string().nullish(),
    email: z.string().nullish(),
    address: z.string().nullish(),
    founded: z.number().nullish(),
  }).nullish(),
  rebate: z.object({
    amount_usd: z.string().nullish(),
    amount_cad: z.string().nullish(),
    expires_at: z.string().nullish(),
  }).nullish(),
  social: z.record(z.string()).nullish(),
});

function buildCollections(locale: string) {
  return {
    [`pages-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx,json}', base: `./src/content/${locale}/pages` }),
      schema: pageSchema,
    }),
    [`blog-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx}', base: `./src/content/${locale}/blog` }),
      schema: blogSchema,
    }),
    [`services-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx,json}', base: `./src/content/${locale}/services` }),
      schema: serviceSchema,
    }),
    [`faq-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx,json}', base: `./src/content/${locale}/faq` }),
      schema: faqSchema,
    }),
    [`settings-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{json,yml,yaml}', base: `./src/content/${locale}/settings` }),
      schema: settingsSchema,
    }),
  };
}

export const collections = {
  ...buildCollections('en'),
  ...buildCollections('es'),
  ...buildCollections('en-ca'),
  ...buildCollections('fr-ca'),
};
