// Astro 5 content collections — locale_routed branch (per Phase 1 handoff §5).
// Each locale gets parallel collections; routes read `pages-{locale}` etc.
// All-auto translation per Phase 5 Turn 1: EN is source of truth, es/en-ca/fr-ca
// are generated by translate-loader at build (Phase 5 §lib/translate-loader.ts).

import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

const pageSchema = z.object({
  title: z.string(),
  description: z.string().nullish(),
  ogImage: z.string().nullish(),
  publishedAt: z.coerce.date().nullish(),
  updatedAt: z.coerce.date().nullish(),
  draft: z.boolean().default(false),
  structuredData: z.any().nullish(),
  content_blocks: z.array(z.object({ _type: z.string() }).passthrough()).default([]),
});

const blogSchema = pageSchema.extend({
  excerpt: z.string().nullish(),
  author: z.string().nullish(),
  category: z.string().nullish(),
  tags: z.array(z.string()).default([]),
  hero: z.string().nullish(),
});

const serviceSchema = z.object({
  title: z.string(),
  summary: z.string().nullish(),
  href: z.string(),
});

const faqSchema = z.object({
  question: z.string(),
  answer: z.string(),
  order: z.number().default(0),
});

const settingsSchema = z.object({
  company: z.object({
    name: z.string().nullish(),
    parent: z.string().nullish(),
    phone: z.string().nullish(),
    email: z.string().nullish(),
    address: z.string().nullish(),
    founded: z.number().nullish(),
  }).nullish(),
  rebate: z.object({
    amount_usd: z.string().nullish(),
    amount_cad: z.string().nullish(),
    expires_at: z.string().nullish(),
  }).nullish(),
  social: z.record(z.string()).nullish(),
});

// Product family. One file per family (e.g. mezzo.json); `sizes` carries variants
// (32/36/48/60/72) rendered as anchor sub-sections on the family page.
const productSchema = z.object({
  title: z.string(),
  description: z.string().nullish(),
  ogImage: z.string().nullish(),
  publishedAt: z.coerce.date().nullish(),
  updatedAt: z.coerce.date().nullish(),
  draft: z.boolean().default(false),
  structuredData: z.any().nullish(),

  family: z.string(),
  energy: z.enum(['gas', 'wood', 'electric']),
  placement: z.string(),
  legacy_slugs: z.array(z.string()).default([]),

  sizes: z.array(z.object({
    id: z.string(),
    name: z.string(),
    width_in: z.string().nullish(),
    height_in: z.string().nullish(),
    depth_in: z.string().nullish(),
    btu_max: z.string().nullish(),
    spec_pdf_url: z.string().nullish(),
    image: z.string().nullish(),
  })).default([]),

  gallery: z.array(z.object({
    src: z.string(),
    alt: z.string().nullish(),
    caption: z.string().nullish(),
  })).default([]),

  complete_the_look: z.array(z.string()).default([]),

  available_in: z.array(z.string()).default(['us']),
  hreflang_locales: z.array(z.string()).default([]),

  hero: z.object({
    eyebrow: z.string().nullish(),
    h1: z.string().nullish(),
    h1_em: z.string().nullish(),
    lede: z.string().nullish(),
  }).nullish(),

  faq: z.array(z.object({
    question: z.string(),
    answer: z.string(),
  })).default([]),

  content_blocks: z.array(z.object({ _type: z.string() }).passthrough()).default([]),
});

// Accessories. `compatible_fireplaces` is a slug list driving the reverse
// cross-reference module on accessory pages back to fireplace family pages.
const accessorySchema = z.object({
  title: z.string(),
  description: z.string().nullish(),
  ogImage: z.string().nullish(),
  draft: z.boolean().default(false),
  structuredData: z.any().nullish(),

  accessory_type: z.enum(['mantel-shelf', 'stone-surround', 'wood-mantel', 'hearth-stone']),
  compatible_fireplaces: z.array(z.string()).default([]),

  gallery: z.array(z.object({
    src: z.string(),
    alt: z.string().nullish(),
    caption: z.string().nullish(),
  })).default([]),

  content_blocks: z.array(z.object({ _type: z.string() }).passthrough()).default([]),
});

function buildCollections(locale: string) {
  return {
    [`pages-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx,json}', base: `./src/content/${locale}/pages` }),
      schema: pageSchema,
    }),
    [`blog-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx}', base: `./src/content/${locale}/blog` }),
      schema: blogSchema,
    }),
    [`services-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx,json}', base: `./src/content/${locale}/services` }),
      schema: serviceSchema,
    }),
    [`faq-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx,json}', base: `./src/content/${locale}/faq` }),
      schema: faqSchema,
    }),
    [`settings-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{json,yml,yaml}', base: `./src/content/${locale}/settings` }),
      schema: settingsSchema,
    }),
    [`products-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx,json}', base: `./src/content/${locale}/products` }),
      schema: productSchema,
    }),
    [`accessories-${locale}`]: defineCollection({
      loader: glob({ pattern: '**/*.{md,mdx,json}', base: `./src/content/${locale}/accessories` }),
      schema: accessorySchema,
    }),
  };
}

export const collections = {
  ...buildCollections('en'),
  ...buildCollections('es'),
  ...buildCollections('en-ca'),
  ...buildCollections('fr-ca'),
};
